# Fichier: ansible/site.yml
---
- name: "MISSION 1: Déploiement Cluster HA (Web & Samba)"
  import_playbook: playbooks/ha_cluster.yml

- name: "MISSION 2: Sécurisation des Nœuds Linux"
  import_playbook: playbooks/security.yml

- name: "MISSION 3: Déploiement Windows (AD & Sécurité)"
  import_playbook: playbooks/windows.yml